/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.github.johnrengelman.shadow") version "6.1.0"
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    jcenter()
}

dependencies {
    implementation("com.sparkjava:spark-core:2.9.2")
    implementation("org.slf4j:slf4j-simple:1.7.25")
    implementation("com.github.ben-manes.caffeine:caffeine:2.8.4")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.11.0")
    implementation("com.squareup.okhttp3:okhttp:3.14.7")
}

group = "org.yatopiamc"
version = "1.0-SNAPSHOT"
description = "Site-API"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

application {
    mainClassName = "org.yatopiamc.site.api.APIBootstrap"
}

tasks {
    build {
        dependsOn(shadowJar)
    }
    shadowJar {
        minimize()
    }
}
